/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Author: typeof import('./components/Author.vue')['default']
    AuthorLinks: typeof import('./components/AuthorLinks.vue')['default']
    BlogPosts: typeof import('./components/BlogPosts.vue')['default']
    BlogTitle: typeof import('./components/BlogTitle.vue')['default']
    FollowLinks: typeof import('./components/FollowLinks.vue')['default']
    GettingStarted: typeof import('./components/GettingStarted.vue')['default']
    MarkdownComponent: typeof import('./components/MarkdownComponent.vue')['default']
    MarkdownPage: typeof import('./components/MarkdownPage.vue')['default']
    NavFooter: typeof import('./components/NavFooter.vue')['default']
    NavHeader: typeof import('./components/NavHeader.vue')['default']
    NavItem: typeof import('./components/NavItem.vue')['default']
    NavLink: typeof import('./components/NavLink.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShellCommand: typeof import('./components/ShellCommand.vue')['default']
    SrcLink: typeof import('./components/SrcLink.vue')['default']
    SrcVuePage: typeof import('./components/SrcVuePage.vue')['default']
    VideoGroup: typeof import('./components/VideoGroup.vue')['default']
  }
}
