/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Author: typeof import('./src/components/Author.vue')['default']
    AuthorLinks: typeof import('./src/components/AuthorLinks.vue')['default']
    BlogPosts: typeof import('./src/components/BlogPosts.vue')['default']
    BlogTitle: typeof import('./src/components/BlogTitle.vue')['default']
    DarkModeToggler: typeof import('./src/components/DarkModeToggler.vue')['default']
    FileLayout: typeof import('./src/components/FileLayout.vue')['default']
    Files: typeof import('./src/components/Files.vue')['default']
    FollowLinks: typeof import('./src/components/FollowLinks.vue')['default']
    GettingStarted: typeof import('./src/components/GettingStarted.vue')['default']
    Include: typeof import('./src/components/Include.vue')['default']
    MarkdownComponent: typeof import('./src/components/MarkdownComponent.vue')['default']
    MarkdownPage: typeof import('./src/components/MarkdownPage.vue')['default']
    NavFooter: typeof import('./src/components/NavFooter.vue')['default']
    NavHeader: typeof import('./src/components/NavHeader.vue')['default']
    NavItem: typeof import('./src/components/NavItem.vue')['default']
    NavLink: typeof import('./src/components/NavLink.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShellCommand: typeof import('./src/components/ShellCommand.vue')['default']
    SrcLink: typeof import('./src/components/SrcLink.vue')['default']
    SrcPage: typeof import('./src/components/SrcPage.vue')['default']
    VideoGroup: typeof import('./src/components/VideoGroup.vue')['default']
  }
}
