/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBreadcrumb: typeof import('./src/components/AppBreadcrumb.vue')['default']
    AppPage: typeof import('./src/components/AppPage.vue')['default']
    GettingStarted: typeof import('./src/components/GettingStarted.vue')['default']
    HelloApi: typeof import('./src/components/HelloApi.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MarkdownPage: typeof import('./src/components/MarkdownPage.vue')['default']
    NavFooter: typeof import('./src/components/NavFooter.vue')['default']
    NavHeader: typeof import('./src/components/NavHeader.vue')['default']
    NavItem: typeof import('./src/components/NavItem.vue')['default']
    NavLink: typeof import('./src/components/NavLink.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShellCommand: typeof import('./src/components/ShellCommand.vue')['default']
    SrcLink: typeof import('./src/components/SrcLink.vue')['default']
  }
}
